name: (GitHub Actions) Cypress（ローカルで実行する）

on:
  # ローカル実行かつパブリックリポジトリなので、全てのケースで実行する
  - push
  # push:
  #   branches:
  #     - main
  #     - development
  # pull_request:
  #   branches:
  #     - development

jobs:
  cypress_figure_dd:
    name: Cypress での E2E テスト
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: 環境を確認する
        run: |
          echo '[$ pwd]'
          pwd
          echo '[$ ls -la]'
          ls -la
      - name: 日本語フォントのインストールを行う
        run: |
          sudo apt install -y fonts-migmix
      # https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian
      - name: Cypress 用のパッケージをインストールする
        run: |
          sudo apt install -y libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
      - name: Node.js をセットアップする
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn
      - name: npm 自身をアップグレードする
        run: |
          echo 'アップグレード前の npm のバージョンは、'
          npm --version
          npm install -g npm
          echo 'アップグレード後の npm のバージョンは、'
          npm --version
      - name: npm-run-all をグローバルにインストールする
        run: |
          npm install -g npm-run-all
      - name: アーティファクト用のディレクトリを作成する
        run: |
          mkdir cypress/videos
          mkdir cypress/screenshots
      - name: Npm のパッケージをインストールする ($ yarn install)
        run: |
          yarn install
      - name: Cypress を実行する
        uses: cypress-io/github-action@v6.9.0
        with:
          start: npx cypress
          working-directory: ./
          config-file: cypress.config.ts
          record: false
          browser: chrome
          # browser: firefox
          # browser: edge
      - name: Cypress のスクリーンショットをアップロードする
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: cypress_screenshots
          path: cypress/screenshots/
      - name: Cypress の動画をアップロードする
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with:
          name: cypress_videos
          path: cypress/videos/
