name: (GitHub Actions) Cypress（SaaS上で実行する）

on:
  # あっという間に無料枠の上限（Test Results 500）に達するので、実質 SaaS では使えない
  - workflow_dispatch
  # push:
  #   branches:
  #     - main
  #     - development
  # pull_request:
  #   branches:
  #     - development

jobs:
  cypress_figure_dd:
    name: Cypress での E2E テスト
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: 環境を確認する
        run: |
          echo '[$ pwd]'
          pwd
          echo '[$ ls -la]'
          ls -la
      - name: Google Noto Fonts のインストールを行う
        run: |
          sudo apt install -y fonts-noto
      - name: Cypress 用のパッケージをインストールする
        run: |
          sudo apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
      - name: libffi7 対策
        run: |
          sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0 /usr/lib/x86_64-linux-gnu/libffi.so.6
      - name: Node.js をインストールする
        run: |
          curl -sSL "https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x64.tar.xz" | tar --strip-components=2 -xJ -C /usr/local/bin/ node-v16.14.2-linux-x64/bin/node
          curl https://www.npmjs.com/install.sh | bash
          echo 'インストールされた Node.js のバージョンは、'
          node -v
          echo 'インストールされた npm のバージョンは、'
          npm -v
      - name: npm 自身をアップグレードする
        run: |
          echo 'アップグレード前の npm のバージョンは、'
          npm --version
          npm install -g npm
          echo 'アップグレード後の npm のバージョンは、'
          npm --version
      - name: npm-run-all をグローバルにインストールする
        run: |
          npm install -g npm-run-all
      - name: Yarn のインストールを行う
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update -y
          sudo apt install -y yarn
      - name: Yarn のキャッシュのパスを取得する
        id: yarn-cache
        run: echo "::set-output name=dir::.yarn/cache"
      - name: Yarn のキャッシュファイルを取得する
        uses: actions/cache@v2.1.6
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Npm のパッケージをインストールする ($ yarn install)
        run: |
          yarn install
      - name: Cypress を実行する
        uses: cypress-io/github-action@v2.11.7
        with:
          working-directory: ./
          config-file: cypress.json
          record: true
          browser: chrome
          # browser: firefox
          # browser: edge
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
