name: (GitHub Actions) Cypress（SaaS上で実行する）

on:
  # あっという間に無料枠の上限（Test Results 500）に達するので、実質 SaaS では使えない
  - workflow_dispatch
  # push:
  #   branches:
  #     - main
  #     - development
  # pull_request:
  #   branches:
  #     - development

jobs:
  cypress_figure_dd:
    name: Cypress での E2E テスト
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: 環境を確認する
        run: |
          echo '[$ pwd]'
          pwd
          echo '[$ ls -la]'
          ls -la
      - name: 日本語フォントのインストールを行う
        run: |
          sudo apt install -y fonts-migmix
      # https://docs.cypress.io/app/get-started/install-cypress#UbuntuDebian
      - name: Cypress 用のパッケージをインストールする
        run: |
          sudo apt install -y libgtk2.0-0t64 libgtk-3-0t64 libgbm-dev libnotify-dev libnss3 libxss1 libasound2t64 libxtst6 xauth xvfb
      - name: Node.js をセットアップする
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn
      - name: npm 自身をアップグレードする
        run: |
          echo 'アップグレード前の npm のバージョンは、'
          npm --version
          npm install -g npm
          echo 'アップグレード後の npm のバージョンは、'
          npm --version
      - name: npm-run-all をグローバルにインストールする
        run: |
          npm install -g npm-run-all
      - name: Npm のパッケージをインストールする ($ yarn install)
        run: |
          yarn install
      - name: Cypress を実行する
        uses: cypress-io/github-action@v6.8.0
        with:
          working-directory: ./
          config-file: cypress.config.ts
          record: true
          browser: chrome
          # browser: firefox
          # browser: edge
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
